export const jsonData = {

  artists: [
    {
      image: '../../../assets/upload/artist/AR-Rehman.png',
      name: 'AR-Rehman',
      profession: 'Musicians',
      rs: '32,484',
    },
    {
      image: '../../../assets/upload/artist/Ajay-Atul.png',
      name: 'Ajay-Atul',
      profession: 'Musicians',
      rs: '32,200',
    },
    {
      image: '../../../assets/upload/artist/Anoushka-Shankar.png',
      name: 'Anoushka-Shankar',
      profession: 'lyricist',
      rs: '32,000',
    },
    {
      image: '../../../assets/upload/artist/Hariprasad-Chaurasia.png',
      name: 'Hariprasad-Chaurasia',
      profession: 'lyricist',
      rs: '60,000',
    },
    {
      image: '../../../assets/upload/artist/Meet-Bros.png',
      name: 'Meet-Bros',
      profession: 'singer',
      rs: '80,000',
    },
  ],

  userDummyData: [
    {
      id: 1,
      firstName: "Terry",
      lastName: "Medhurst",
      maidenName: "Smitham",
      age: 50,
      gender: "male",
      email: "atuny0@sohu.com",
      phone: "+63 791 675 8914",
      username: "atuny0",
      password: "9uQFF1Lh",
      birthDate: "2000-12-25",
      image: "https://robohash.org/hicveldicta.png",
      bloodGroup: "A−",
      height: 189,
      weight: 75.4,
      eyeColor: "Green",
      hair: {
        color: "Black",
        type: "Strands",
      },
      domain: "slashdot.org",
      ip: "117.29.86.254",
      address: {
        address: "1745 T Street Southeast",
        city: "Washington",
        coordinates: {
          lat: 38.867033,
          lng: -76.979235,
        },
        postalCode: "20020",
        state: "DC",
      },
      macAddress: "13:69:BA:56:A3:74",
      university: "Capitol University",
      bank: {
        cardExpire: "06/22",
        cardNumber: "50380955204220685",
        cardType: "maestro",
        currency: "Peso",
        iban: "NO17 0695 2754 967",
      },
      company: {
        address: {
          address: "629 Debbie Drive",
          city: "Nashville",
          coordinates: {
            lat: 36.208114,
            lng: -86.58621199999999,
          },
          postalCode: "37076",
          state: "TN",
        },
        department: "Marketing",
        name: "Blanda-O'Keefe",
        title: "Help Desk Operator",
      },
      ein: "20-9487066",
      ssn: "661-64-2976",
      userAgent:
        "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/12.0.702.0 Safari/534.24",
    },
    {
      id: 2,
      firstName: "Sheldon",
      lastName: "Quigley",
      maidenName: "Cole",
      age: 28,
      gender: "male",
      email: "hbingley1@plala.or.jp",
      phone: "+7 813 117 7139",
      username: "hbingley1",
      password: "CQutx25i8r",
      birthDate: "2003-08-02",
      image: "https://robohash.org/doloremquesintcorrupti.png",
      bloodGroup: "O+",
      height: 187,
      weight: 74,
      eyeColor: "Brown",
      hair: {
        color: "Blond",
        type: "Curly",
      },
      domain: "51.la",
      ip: "253.240.20.181",
      address: {
        address: "6007 Applegate Lane",
        city: "Louisville",
        coordinates: {
          lat: 38.1343013,
          lng: -85.6498512,
        },
        postalCode: "40219",
        state: "KY",
      },
      macAddress: "13:F1:00:DA:A4:12",
      university: "Stavropol State Technical University",
      bank: {
        cardExpire: "10/23",
        cardNumber: "5355920631952404",
        cardType: "mastercard",
        currency: "Ruble",
        iban: "MD63 L6YC 8YH4 QVQB XHIK MTML",
      },
      company: {
        address: {
          address: "8821 West Myrtle Avenue",
          city: "Glendale",
          coordinates: {
            lat: 33.5404296,
            lng: -112.2488391,
          },
          postalCode: "85305",
          state: "AZ",
        },
        department: "Services",
        name: "Aufderhar-Cronin",
        title: "Senior Cost Accountant",
      },
      ein: "52-5262907",
      ssn: "447-08-9217",
      userAgent:
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.30 (KHTML, like Gecko) Ubuntu/11.04 Chromium/12.0.742.112 Chrome/12.0.742.112 Safari/534.30",
    },
    {
      id: 3,
      firstName: "Terrill",
      lastName: "Hills",
      maidenName: "Hoeger",
      age: 38,
      gender: "male",
      email: "rshawe2@51.la",
      phone: "+63 739 292 7942",
      username: "rshawe2",
      password: "OWsTbMUgFc",
      birthDate: "1992-12-30",
      image: "https://robohash.org/consequunturautconsequatur.png",
      bloodGroup: "A−",
      height: 200,
      weight: 105.3,
      eyeColor: "Gray",
      hair: {
        color: "Blond",
        type: "Very curly",
      },
      domain: "earthlink.net",
      ip: "205.226.160.3",
      address: {
        address: "560 Penstock Drive",
        city: "Grass Valley",
        coordinates: {
          lat: 39.213076,
          lng: -121.077583,
        },
        postalCode: "95945",
        state: "CA",
      },
      macAddress: "F2:88:58:64:F7:76",
      university: "University of Cagayan Valley",
      bank: {
        cardExpire: "10/23",
        cardNumber: "3586082982526703",
        cardType: "jcb",
        currency: "Peso",
        iban: "AT24 1095 9625 1434 9703",
      },
      company: {
        address: {
          address: "18 Densmore Drive",
          city: "Essex",
          coordinates: {
            lat: 44.492953,
            lng: -73.101883,
          },
          postalCode: "05452",
          state: "VT",
        },
        department: "Marketing",
        name: "Lindgren LLC",
        title: "Mechanical Systems Engineer",
      },
      ein: "48-3951994",
      ssn: "633-89-1926",
      userAgent:
        "Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:21.0.0) Gecko/20121011 Firefox/21.0.0",
    },
    {
      id: 4,
      firstName: "Miles",
      lastName: "Cummerata",
      maidenName: "Maggio",
      age: 49,
      gender: "male",
      email: "yraigatt3@nature.com",
      phone: "+86 461 145 4186",
      username: "yraigatt3",
      password: "sRQxjPfdS",
      birthDate: "1969-01-16",
      image: "https://robohash.org/facilisdignissimosdolore.png",
      bloodGroup: "B+",
      height: 157,
      weight: 95.9,
      eyeColor: "Gray",
      hair: {
        color: "Blond",
        type: "Very curly",
      },
      domain: "homestead.com",
      ip: "243.20.78.113",
      address: {
        address: "150 Carter Street",
        city: "Manchester",
        coordinates: {
          lat: 41.76556000000001,
          lng: -72.473091,
        },
        postalCode: "06040",
        state: "CT",
      },
      macAddress: "03:45:58:59:5A:7B",
      university: "Shenyang Pharmaceutical University",
      bank: {
        cardExpire: "07/24",
        cardNumber: "3580047879369323",
        cardType: "jcb",
        currency: "Yuan Renminbi",
        iban: "KZ43 658B M6VS TZOU OXSO",
      },
      company: {
        address: {
          address: "210 Green Road",
          city: "Manchester",
          coordinates: {
            lat: 41.7909099,
            lng: -72.51195129999999,
          },
          postalCode: "06042",
          state: "CT",
        },
        department: "Business Development",
        name: "Wolff and Sons",
        title: "Paralegal",
      },
      ein: "71-3644334",
      ssn: "487-28-6642",
      userAgent:
        "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.17 Safari/537.11",
    },
    {
      id: 5,
      firstName: "Mavis",
      lastName: "Schultz",
      maidenName: "Yundt",
      age: 38,
      gender: "male",
      email: "kmeus4@upenn.edu",
      phone: "+372 285 771 1911",
      username: "kmeus4",
      password: "aUTdmmmbH",
      birthDate: "1968-11-03",
      image: "https://robohash.org/adverovelit.png",
      bloodGroup: "O+",
      height: 188,
      weight: 106.3,
      eyeColor: "Brown",
      hair: {
        color: "Brown",
        type: "Curly",
      },
      domain: "columbia.edu",
      ip: "103.72.86.183",
      address: {
        address: "2721 Lindsay Avenue",
        city: "Louisville",
        coordinates: {
          lat: 38.263793,
          lng: -85.700243,
        },
        postalCode: "40206",
        state: "KY",
      },
      macAddress: "F8:04:9E:ED:C0:68",
      university: "Estonian University of Life Sciences",
      bank: {
        cardExpire: "01/24",
        cardNumber: "4917245076693618",
        cardType: "visa-electron",
        currency: "Euro",
        iban: "IT41 T114 5127 716J RGYB ZRUX DSJ",
      },
      company: {
        address: {
          address: "8398 West Denton Lane",
          city: "Glendale",
          coordinates: {
            lat: 33.515353,
            lng: -112.240812,
          },
          postalCode: "85305",
          state: "AZ",
        },
        department: "Support",
        name: "Adams Inc",
        title: "Web Developer I",
      },
      ein: "18-7178563",
      ssn: "667-98-5357",
      userAgent:
        "Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.1 Safari/535.1",
    },
    {
      id: 6,
      firstName: "Alison",
      lastName: "Reichert",
      maidenName: "Franecki",
      age: 21,
      gender: "female",
      email: "jtreleven5@nhs.uk",
      phone: "+351 527 735 3642",
      username: "jtreleven5",
      password: "zY1nE46Zm",
      birthDate: "1969-07-21",
      image: "https://robohash.org/laboriosamfacilisrem.png",
      bloodGroup: "A+",
      height: 149,
      weight: 105.7,
      eyeColor: "Amber",
      hair: {
        color: "Blond",
        type: "Straight",
      },
      domain: "bandcamp.com",
      ip: "49.201.206.36",
      address: {
        address: "18 Densmore Drive",
        city: "Essex",
        coordinates: {
          lat: 44.492953,
          lng: -73.101883,
        },
        postalCode: "05452",
        state: "VT",
      },
      macAddress: "6C:34:D0:4B:4E:81",
      university: "Universidade da Beira Interior",
      bank: {
        cardExpire: "03/22",
        cardNumber: "345675888286047",
        cardType: "americanexpress",
        currency: "Euro",
        iban: "LB69 1062 QCY5 XS5T VOKU KJFG XP4S",
      },
      company: {
        address: {
          address: "6231 North 67th Avenue",
          city: "Glendale",
          coordinates: {
            lat: 33.5279666,
            lng: -112.2022551,
          },
          postalCode: "85301",
          state: "AZ",
        },
        department: "Accounting",
        name: "D'Amore and Sons",
        title: "Civil Engineer",
      },
      ein: "78-3192791",
      ssn: "158-68-0184",
      userAgent:
        "Mozilla/5.0 (Windows; U; Windows NT 6.0; nb-NO) AppleWebKit/533.18.1 (KHTML, like Gecko) Version/5.0.2 Safari/533.18.5",
    },
    {
      id: 7,
      firstName: "Oleta",
      lastName: "Abbott",
      maidenName: "Wyman",
      age: 31,
      gender: "female",
      email: "dpettegre6@columbia.edu",
      phone: "+62 640 802 7111",
      username: "dpettegre6",
      password: "YVmhktgYVS",
      birthDate: "1982-02-21",
      image: "https://robohash.org/cupiditatererumquos.png",
      bloodGroup: "B−",
      height: 172,
      weight: 78.1,
      eyeColor: "Blue",
      hair: {
        color: "Chestnut",
        type: "Wavy",
      },
      domain: "ovh.net",
      ip: "25.207.107.146",
      address: {
        address: "637 Britannia Drive",
        city: "Vallejo",
        coordinates: {
          lat: 38.10476999999999,
          lng: -122.193849,
        },
        postalCode: "94591",
        state: "CA",
      },
      macAddress: "48:2D:A0:67:19:E0",
      university: "Institut Sains dan Teknologi Al Kamal",
      bank: {
        cardExpire: "10/23",
        cardNumber: "3589640949470047",
        cardType: "jcb",
        currency: "Rupiah",
        iban: "GI97 IKPF 9DUO X25M FG8D UXY",
      },
      company: {
        address: {
          address: "1407 Walden Court",
          city: "Crofton",
          coordinates: {
            lat: 39.019306,
            lng: -76.660653,
          },
          postalCode: "21114",
          state: "MD",
        },
        department: "Product Management",
        name: "Schimmel, Wilderman and Orn",
        title: "Sales Associate",
      },
      ein: "29-1568401",
      ssn: "478-11-2206",
      userAgent:
        "Mozilla/5.0 (Windows; U; Windows NT 5.1; ru-RU) AppleWebKit/533.18.1 (KHTML, like Gecko) Version/5.0.2 Safari/533.18.5",
    },
    {
      id: 8,
      firstName: "Ewell",
      lastName: "Mueller",
      maidenName: "Durgan",
      age: 29,
      gender: "male",
      email: "ggude7@chron.com",
      phone: "+86 946 297 2275",
      username: "ggude7",
      password: "MWwlaeWcOoF6",
      birthDate: "1964-08-24",
      image: "https://robohash.org/quiaharumsapiente.png",
      bloodGroup: "A−",
      height: 146,
      weight: 52.1,
      eyeColor: "Blue",
      hair: {
        color: "Chestnut",
        type: "Wavy",
      },
      domain: "homestead.com",
      ip: "91.200.56.127",
      address: {
        address: "5601 West Crocus Drive",
        city: "Glendale",
        coordinates: {
          lat: 33.6152469,
          lng: -112.179737,
        },
        postalCode: "85306",
        state: "AZ",
      },
      macAddress: "72:DA:1B:D7:30:E9",
      university: "Wenzhou Medical College",
      bank: {
        cardExpire: "09/23",
        cardNumber: "30549925358905",
        cardType: "diners-club-carte-blanche",
        currency: "Yuan Renminbi",
        iban: "CY02 9914 5346 0PMT G6XW TP0R AWRZ",
      },
      company: {
        address: {
          address: "81 Seaton Place Northwest",
          city: "Washington",
          coordinates: {
            lat: 38.9149499,
            lng: -77.01170259999999,
          },
          postalCode: "20001",
          state: "DC",
        },
        department: "Services",
        name: "Corkery, Reichert and Hodkiewicz",
        title: "Clinical Specialist",
      },
      ein: "88-4396827",
      ssn: "238-41-5528",
      userAgent:
        "Mozilla/5.0 (X11; Linux amd64) AppleWebKit/534.36 (KHTML, like Gecko) Chrome/13.0.766.0 Safari/534.36",
    },
    {
      id: 9,
      firstName: "Demetrius",
      lastName: "Corkery",
      maidenName: "Gleason",
      age: 22,
      gender: "male",
      email: "nloiterton8@aol.com",
      phone: "+86 356 590 9727",
      username: "nloiterton8",
      password: "HTQxxXV9Bq4",
      birthDate: "1971-03-11",
      image: "https://robohash.org/excepturiiuremolestiae.png",
      bloodGroup: "A+",
      height: 170,
      weight: 97.1,
      eyeColor: "Green",
      hair: {
        color: "Brown",
        type: "Strands",
      },
      domain: "goodreads.com",
      ip: "78.170.185.120",
      address: {
        address: "5403 Illinois Avenue",
        city: "Nashville",
        coordinates: {
          lat: 36.157077,
          lng: -86.853827,
        },
        postalCode: "37209",
        state: "TN",
      },
      macAddress: "98:EE:94:A2:91:C4",
      university: "Nanjing University of Economics",
      bank: {
        cardExpire: "02/24",
        cardNumber: "5372664789004621",
        cardType: "mastercard",
        currency: "Yuan Renminbi",
        iban: "BR68 9829 0581 3669 5088 5533 025N V",
      },
      company: {
        address: {
          address: "12245 West 71st Place",
          city: "Arvada",
          coordinates: {
            lat: 39.8267078,
            lng: -105.1366798,
          },
          postalCode: "80004",
          state: "CO",
        },
        department: "Human Resources",
        name: "Gorczany Group",
        title: "Community Outreach Specialist",
      },
      ein: "14-1066382",
      ssn: "717-26-3759",
      userAgent:
        "Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_4_11; de) AppleWebKit/528.4+ (KHTML, like Gecko) Version/4.0dp1 Safari/526.11.2",
    },
    {
      id: 10,
      firstName: "Eleanora",
      lastName: "Price",
      maidenName: "Cummings",
      age: 37,
      gender: "female",
      email: "umcgourty9@jalbum.net",
      phone: "+60 184 408 0824",
      username: "umcgourty9",
      password: "i0xzpX",
      birthDate: "1958-08-11",
      image: "https://robohash.org/aliquamcumqueiure.png",
      bloodGroup: "O+",
      height: 198,
      weight: 48,
      eyeColor: "Blue",
      hair: {
        color: "Chestnut",
        type: "Wavy",
      },
      domain: "alibaba.com",
      ip: "73.15.179.178",
      address: {
        address: "8821 West Myrtle Avenue",
        city: "Glendale",
        coordinates: {
          lat: 33.5404296,
          lng: -112.2488391,
        },
        postalCode: "85305",
        state: "AZ",
      },
      macAddress: "BC:A9:D8:98:CB:0B",
      university: "Melaka City Polytechnic",
      bank: {
        cardExpire: "01/24",
        cardNumber: "3557806620295254",
        cardType: "jcb",
        currency: "Ringgit",
        iban: "GT40 DWAD 9UHA VEOZ ZF4J 2Y0F OOFD",
      },
      company: {
        address: {
          address: "1649 Timberridge Court",
          city: "Fayetteville",
          coordinates: {
            lat: 36.084563,
            lng: -94.206082,
          },
          postalCode: "72704",
          state: "AR",
        },
        department: "Marketing",
        name: "Bins Group",
        title: "Senior Sales Associate",
      },
      ein: "21-5278484",
      ssn: "544-66-0745",
      userAgent:
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.6 Safari/537.11",
    },
    {
      id: 11,
      firstName: "Marcel",
      lastName: "Jones",
      maidenName: "Smith",
      age: 39,
      gender: "male",
      email: "acharlota@liveinternet.ru",
      phone: "+967 253 210 0344",
      username: "acharlota",
      password: "M9lbMdydMN",
      birthDate: "1961-09-12",
      image: "https://robohash.org/impeditautest.png",
      bloodGroup: "B−",
      height: 203,
      weight: 63.7,
      eyeColor: "Amber",
      hair: {
        color: "Black",
        type: "Straight",
      },
      domain: "feedburner.com",
      ip: "137.235.164.173",
      address: {
        address: "2203 7th Street Road",
        city: "Louisville",
        coordinates: {
          lat: 38.218107,
          lng: -85.779006,
        },
        postalCode: "40208",
        state: "KY",
      },
      macAddress: "59:E8:70:5A:E5:D6",
      university: "Hodeidah University",
      bank: {
        cardExpire: "05/24",
        cardNumber: "5893925889459720",
        cardType: "maestro",
        currency: "Rial",
        iban: "NL97 UWMY 2503 2999 43",
      },
      company: {
        address: {
          address: "308 Woodleaf Court",
          city: "Glen Burnie",
          coordinates: {
            lat: 39.1425931,
            lng: -76.6238441,
          },
          postalCode: "21061",
          state: "MD",
        },
        department: "Business Development",
        name: "Kuhn-Harber",
        title: "Account Executive",
      },
      ein: "09-3791007",
      ssn: "342-54-8422",
      userAgent:
        "Mozilla/5.0 (Windows NT 5.2) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.792.0 Safari/535.1",
    },
    {
      id: 12,
      firstName: "Assunta",
      lastName: "Rath",
      maidenName: "Heller",
      age: 42,
      gender: "female",
      email: "rhallawellb@dropbox.com",
      phone: "+380 962 542 6549",
      username: "rhallawellb",
      password: "esTkitT1r",
      birthDate: "1990-12-14",
      image: "https://robohash.org/namquaerataut.png",
      bloodGroup: "O−",
      height: 168,
      weight: 96.8,
      eyeColor: "Gray",
      hair: {
        color: "Black",
        type: "Very curly",
      },
      domain: "123-reg.co.uk",
      ip: "74.80.53.208",
      address: {
        address: "6463 Vrain Street",
        city: "Arvada",
        coordinates: {
          lat: 39.814056,
          lng: -105.046913,
        },
        postalCode: "80003",
        state: "CO",
      },
      macAddress: "9B:DC:21:C2:30:A3",
      university: "Kiev Slavonic University",
      bank: {
        cardExpire: "09/22",
        cardNumber: "5602230671060360",
        cardType: "bankcard",
        currency: "Hryvnia",
        iban: "KW76 VNLA LX0Y DMDE PFS8 FVKP VMDF AV",
      },
      company: {
        address: {
          address: "388 East Main Street",
          coordinates: {
            lat: 43.9727945,
            lng: -73.1023187,
          },
          postalCode: "05753",
          state: "VT",
        },
        department: "Product Management",
        name: "Goodwin-Skiles",
        title: "Developer II",
      },
      ein: "14-1242349",
      ssn: "116-51-6131",
      userAgent:
        "Mozilla/5.0 (X11; CrOS i686 4319.74.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.57 Safari/537.36",
    },
    {
      id: 13,
      firstName: "Trace",
      lastName: "Douglas",
      maidenName: "Lemke",
      age: 26,
      gender: "male",
      email: "lgribbinc@posterous.com",
      phone: "+1 609 937 3468",
      username: "lgribbinc",
      password: "ftGj8LZTtv9g",
      birthDate: "1967-07-23",
      image: "https://robohash.org/voluptatemsintnulla.png",
      bloodGroup: "O+",
      height: 181,
      weight: 56.5,
      eyeColor: "Amber",
      hair: {
        color: "Auburn",
        type: "Straight",
      },
      domain: "histats.com",
      ip: "163.245.232.27",
      address: {
        address: "87 Horseshoe Drive",
        city: "West Windsor",
        coordinates: {
          lat: 43.4731793,
          lng: -72.4967532,
        },
        postalCode: "05037",
        state: "VT",
      },
      macAddress: "B9:21:ED:9F:B8:9E",
      university: "Dallas Christian College",
      bank: {
        cardExpire: "01/23",
        cardNumber: "3556299106119514",
        cardType: "jcb",
        currency: "Dollar",
        iban: "AE47 4194 4544 3401 3419 286",
      },
      company: {
        address: {
          address: "310 Timrod Road",
          city: "Manchester",
          coordinates: {
            lat: 41.756758,
            lng: -72.493501,
          },
          postalCode: "06040",
          state: "CT",
        },
        department: "Research and Development",
        name: "Casper Inc",
        title: "Sales Associate",
      },
      ein: "94-0648182",
      ssn: "217-05-3082",
      userAgent:
        "Mozilla/5.0 (Windows; U; Windows NT 5.1; ru-RU) AppleWebKit/533.19.4 (KHTML, like Gecko) Version/5.0.3 Safari/533.19.4",
    },
    {
      id: 14,
      firstName: "Enoch",
      lastName: "Lynch",
      maidenName: "Heidenreich",
      age: 21,
      gender: "male",
      email: "mturleyd@tumblr.com",
      phone: "+94 912 100 5118",
      username: "mturleyd",
      password: "GyLnCB8gNIp",
      birthDate: "1979-08-25",
      image: "https://robohash.org/quisequienim.png",
      bloodGroup: "O+",
      height: 150,
      weight: 100.3,
      eyeColor: "Green",
      hair: {
        color: "Auburn",
        type: "Strands",
      },
      domain: "icio.us",
      ip: "174.238.43.126",
      address: {
        address: "60 Desousa Drive",
        city: "Manchester",
        coordinates: {
          lat: 41.7409259,
          lng: -72.5619104,
        },
        postalCode: "06040",
        state: "CT",
      },
      macAddress: "52:11:E1:31:35:C1",
      university: "University of Sri Jayawardenapura",
      bank: {
        cardExpire: "11/23",
        cardNumber: "5339467937996728",
        cardType: "mastercard",
        currency: "Rupee",
        iban: "SI28 0812 7967 0952 944",
      },
      company: {
        address: {
          address: "21950 Arnold Center Road",
          city: "Carson",
          coordinates: {
            lat: 33.8272706,
            lng: -118.2302826,
          },
          postalCode: "90810",
          state: "CA",
        },
        department: "Sales",
        name: "Schoen Inc",
        title: "Professor",
      },
      ein: "61-8316825",
      ssn: "742-81-1714",
      userAgent:
        "Mozilla/5.0 (Windows; U; Windows NT 5.0; en-en) AppleWebKit/533.16 (KHTML, like Gecko) Version/4.1 Safari/533.16",
    },
    {
      id: 15,
      firstName: "Jeanne",
      lastName: "Halvorson",
      maidenName: "Cummerata",
      age: 26,
      gender: "female",
      email: "kminchelle@qq.com",
      phone: "+86 581 108 7855",
      username: "kminchelle",
      password: "0lelplR",
      birthDate: "1996-02-02",
      image: "https://robohash.org/autquiaut.png",
      bloodGroup: "A+",
      height: 176,
      weight: 45.7,
      eyeColor: "Amber",
      hair: {
        color: "Blond",
        type: "Straight",
      },
      domain: "google.co.uk",
      ip: "78.43.74.226",
      address: {
        address: "4 Old Colony Way",
        city: "Yarmouth",
        coordinates: {
          lat: 41.697168,
          lng: -70.189992,
        },
        postalCode: "02664",
        state: "MA",
      },
      macAddress: "D9:DB:D9:5A:01:09",
      university: "Donghua University, Shanghai",
      bank: {
        cardExpire: "10/23",
        cardNumber: "3588859507772914",
        cardType: "jcb",
        currency: "Yuan Renminbi",
        iban: "FO12 1440 0396 8902 56",
      },
      company: {
        address: {
          address: "22572 Toreador Drive",
          city: "Salinas",
          coordinates: {
            lat: 36.602449,
            lng: -121.699071,
          },
          postalCode: "93908",
          state: "CA",
        },
        department: "Marketing",
        name: "Hahn-MacGyver",
        title: "Software Test Engineer IV",
      },
      ein: "62-0561095",
      ssn: "855-43-8639",
      userAgent:
        "Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.14 Safari/534.24",
    },
  ],

  productDummyData: [
    {
      "id": 1,
      "title": "iPhone 9",
      "description": "An apple mobile which is nothing like apple",
      "price": 549,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "smartphones",
      "thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
      "images": [
        "https://i.dummyjson.com/data/products/1/1.jpg",
        "https://i.dummyjson.com/data/products/1/2.jpg",
        "https://i.dummyjson.com/data/products/1/3.jpg",
        "https://i.dummyjson.com/data/products/1/4.jpg",
        "https://i.dummyjson.com/data/products/1/thumbnail.jpg"
      ]
    },
    {
      "id": 2,
      "title": "iPhone X",
      "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
      "price": 899,
      "discountPercentage": 17.94,
      "rating": 4.44,
      "stock": 34,
      "brand": "Apple",
      "category": "smartphones",
      "thumbnail": "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
      "images": [
        "https://i.dummyjson.com/data/products/2/1.jpg",
        "https://i.dummyjson.com/data/products/2/2.jpg",
        "https://i.dummyjson.com/data/products/2/3.jpg",
        "https://i.dummyjson.com/data/products/2/thumbnail.jpg"
      ]
    },
    {
      "id": 3,
      "title": "Samsung Universe 9",
      "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
      "price": 1249,
      "discountPercentage": 15.46,
      "rating": 4.09,
      "stock": 36,
      "brand": "Samsung",
      "category": "smartphones",
      "thumbnail": "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
      "images": [
        "https://i.dummyjson.com/data/products/3/1.jpg"
      ]
    },
    {
      "id": 4,
      "title": "OPPOF19",
      "description": "OPPO F19 is officially announced on April 2021.",
      "price": 280,
      "discountPercentage": 17.91,
      "rating": 4.3,
      "stock": 123,
      "brand": "OPPO",
      "category": "smartphones",
      "thumbnail": "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
      "images": [
        "https://i.dummyjson.com/data/products/4/1.jpg",
        "https://i.dummyjson.com/data/products/4/2.jpg",
        "https://i.dummyjson.com/data/products/4/3.jpg",
        "https://i.dummyjson.com/data/products/4/4.jpg",
        "https://i.dummyjson.com/data/products/4/thumbnail.jpg"
      ]
    },
    {
      "id": 5,
      "title": "Huawei P30",
      "description": "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
      "price": 499,
      "discountPercentage": 10.58,
      "rating": 4.09,
      "stock": 32,
      "brand": "Huawei",
      "category": "smartphones",
      "thumbnail": "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
      "images": [
        "https://i.dummyjson.com/data/products/5/1.jpg",
        "https://i.dummyjson.com/data/products/5/2.jpg",
        "https://i.dummyjson.com/data/products/5/3.jpg"
      ]
    },
    {
      "id": 6,
      "title": "MacBook Pro",
      "description": "MacBook Pro 2021 with mini-LED display may launch between September, November",
      "price": 1749,
      "discountPercentage": 11.02,
      "rating": 4.57,
      "stock": 83,
      "brand": "Apple",
      "category": "laptops",
      "thumbnail": "https://i.dummyjson.com/data/products/6/thumbnail.png",
      "images": [
        "https://i.dummyjson.com/data/products/6/1.png",
        "https://i.dummyjson.com/data/products/6/2.jpg",
        "https://i.dummyjson.com/data/products/6/3.png",
        "https://i.dummyjson.com/data/products/6/4.jpg"
      ]
    },
    {
      "id": 7,
      "title": "Samsung Galaxy Book",
      "description": "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
      "price": 1499,
      "discountPercentage": 4.15,
      "rating": 4.25,
      "stock": 50,
      "brand": "Samsung",
      "category": "laptops",
      "thumbnail": "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      "images": [
        "https://i.dummyjson.com/data/products/7/1.jpg",
        "https://i.dummyjson.com/data/products/7/2.jpg",
        "https://i.dummyjson.com/data/products/7/3.jpg",
        "https://i.dummyjson.com/data/products/7/thumbnail.jpg"
      ]
    },
    {
      "id": 8,
      "title": "Microsoft Surface Laptop 4",
      "description": "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
      "price": 1499,
      "discountPercentage": 10.23,
      "rating": 4.43,
      "stock": 68,
      "brand": "Microsoft Surface",
      "category": "laptops",
      "thumbnail": "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
      "images": [
        "https://i.dummyjson.com/data/products/8/1.jpg",
        "https://i.dummyjson.com/data/products/8/2.jpg",
        "https://i.dummyjson.com/data/products/8/3.jpg",
        "https://i.dummyjson.com/data/products/8/4.jpg",
        "https://i.dummyjson.com/data/products/8/thumbnail.jpg"
      ]
    },
    {
      "id": 9,
      "title": "Infinix INBOOK",
      "description": "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
      "price": 1099,
      "discountPercentage": 11.83,
      "rating": 4.54,
      "stock": 96,
      "brand": "Infinix",
      "category": "laptops",
      "thumbnail": "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
      "images": [
        "https://i.dummyjson.com/data/products/9/1.jpg",
        "https://i.dummyjson.com/data/products/9/2.png",
        "https://i.dummyjson.com/data/products/9/3.png",
        "https://i.dummyjson.com/data/products/9/4.jpg",
        "https://i.dummyjson.com/data/products/9/thumbnail.jpg"
      ]
    },
    {
      "id": 10,
      "title": "HP Pavilion 15-DK1056WM",
      "description": "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
      "price": 1099,
      "discountPercentage": 6.18,
      "rating": 4.43,
      "stock": 89,
      "brand": "HP Pavilion",
      "category": "laptops",
      "thumbnail": "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
      "images": [
        "https://i.dummyjson.com/data/products/10/1.jpg",
        "https://i.dummyjson.com/data/products/10/2.jpg",
        "https://i.dummyjson.com/data/products/10/3.jpg",
        "https://i.dummyjson.com/data/products/10/thumbnail.jpeg"
      ]
    },
    {
      "id": 11,
      "title": "perfume Oil",
      "description": "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
      "price": 13,
      "discountPercentage": 8.4,
      "rating": 4.26,
      "stock": 65,
      "brand": "Impression of Acqua Di Gio",
      "category": "fragrances",
      "thumbnail": "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
      "images": [
        "https://i.dummyjson.com/data/products/11/1.jpg",
        "https://i.dummyjson.com/data/products/11/2.jpg",
        "https://i.dummyjson.com/data/products/11/3.jpg",
        "https://i.dummyjson.com/data/products/11/thumbnail.jpg"
      ]
    },
    {
      "id": 12,
      "title": "Brown Perfume",
      "description": "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
      "price": 40,
      "discountPercentage": 15.66,
      "rating": 4,
      "stock": 52,
      "brand": "Royal_Mirage",
      "category": "fragrances",
      "thumbnail": "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
      "images": [
        "https://i.dummyjson.com/data/products/12/1.jpg",
        "https://i.dummyjson.com/data/products/12/2.jpg",
        "https://i.dummyjson.com/data/products/12/3.png",
        "https://i.dummyjson.com/data/products/12/4.jpg",
        "https://i.dummyjson.com/data/products/12/thumbnail.jpg"
      ]
    },
  ],

  suppliersDummyData: [
    {
      "id": "GGOEAFKA087499",
      "name": "Android Small Removable Sticker Sheet",
      "description": "Show your Android pride by placing these 8 fun stickers on your technology products or accessories!",
      "features": "<p>8 Android stickers</p>\n<p>White colored sticker sheet</p>",
      "price": "2.99",
      "keywords": "Android Small Removable Sticker Sheet, android stickers, sticker sheets, removable sticker sheets, small sticker sheet, android small sticker sheets, Android Sheet",
      "url": "Android+Small+Removable+Sticker+Sheet",
      "category": "accessories",
      "subcategory": "accessories"
    },
    {
      "id": "GGOEAFKA087599",
      "name": "Android Large Removable Sticker Sheet",
      "description": "Show your quirky side by placing these fun Android stickers on your personal belongings.",
      "features": "<p>Android Stickers</p>\n<p>White Colored Sticker Sheet</p>",
      "price": "2.99",
      "keywords": "Android Large Removable Sticker Sheet, android stickers, sticker sheets, removable sticker sheets, large sticker sheet, android large sticker sheets, Android Sheet",
      "url": "Android+Large+Removable+Sticker+Sheet",
      "category": "accessories",
      "subcategory": "accessories"
    },
    {
      "id": "GGOEGEBK094499",
      "name": "Google Bot",
      "description": "This Google Bot can hold multiple poses making it a fun toy for all. Fold the Google Bot back up into a perfect cube when you are done playing.",
      "features": "<p>Made of wood</p>\n<p>2.5 x 2.5 inch cube</p>\n<p>6.75 inch tall</p>\n<p>Recommended for Ages 3+</p>",
      "price": "9.99",
      "keywords": "Google Bot, google bot, bots, natural bots, wood bot, google wood bot",
      "url": "Google+Bot",
      "category": "accessories",
      "subcategory": "accessories"
    },
    {
      "id": "GGOEGFKA086699",
      "name": "Google Emoji Sticker Pack",
      "description": "Who doesn't use emojis? Decorate your space with your current mood!",
      "features": "<p>Pack contains two sticker sheets</p>\n<p>Each Sheet has different emojis</p>\n<p><span>Decal dimensions should fit in a maximum sheet size of 12 3/4 x 17 1/2 inch.</span></p>",
      "price": "4.99",
      "keywords": "Google Emoji Sticker Pack, Google sticker pack, emoji sticker pack, google emoji, stickers, pack of sticker, pack of emoji stickers",
      "url": "Google+Emoji+Sticker+Pack+2+sheet",
      "category": "accessories",
      "subcategory": "accessories"
    },
    {
      "id": "GGOEWCKQ085457",
      "name": "Waze Pack of 9 Decal Set",
      "description": "Can't decide which Waze decal to get? We have made that decision easier for you! Now you can purchase a pack of nine Waze Mood Decals!",
      "features": "<p>Pack of 9 includes:</p>\n<p>3 Waze Mood Happy decals</p>\n<p>3 Waze Mood Original decals</p>\n<p>3 Waze Mood Ninja decals</p>",
      "price": "16.99",
      "keywords": "Waze Pack of 9 Decal Set, decals pack, packs of 9, Waze Packs, Waze Decals, waze, Waze",
      "url": "Waze+Pack+of+9+decal+set",
      "category": "accessories",
      "subcategory": "accessories"
    },
    {
      "id": "GGOEGHPB071610",
      "name": "Google Twill Cap",
      "description": "Classic urban styling distinguishes this Google cap. Retains its shape, even when not being worn.",
      "features": "<p>Heavy weight brushed twill</p>\n<p>Adjustable velcro closure</p>\n<p>One size fits all</p>",
      "price": "10.99",
      "keywords": "Google Twill Cap, Google Cap, Google Twill Caps, Google Twill, google cap, google caps, google twill, google twill black cap, google black caps, google caps, black caps, Google Caps",
      "url": "Google+Twill+Cap",
      "category": "apparel",
      "subcategory": "apparel"
    },
    {
      "id": "GGOEGHPJ094299",
      "name": "Google Fold-over Beanie Grey",
      "description": "Keep you ears warm while enjoying a cold winter day with this Google Fold-over Beanie.",
      "features": "<p>100% acrylic</p>\n<p>One size fits all</p>",
      "price": "9.99",
      "keywords": "Google Fold-over Beanie Grey, gray beanie, grey beanie, Google Beanies, Fold over grey, Google Beanie Grey, Google headgear",
      "url": "Google+Fold+over+beanie+grey",
      "category": "apparel",
      "subcategory": "apparel"
    },
    {
      "id": "GGOEGHPJ094399",
      "name": "Google Pom Beanie Charcoal",
      "description": "Stay stylish and warm this winter season with this Google Pom Beanie.",
      "features": "<p>Thick knit texture outside</p>\n<p>Soft plush inside</p>\n<p>Faux fur pom on top</p>",
      "price": "19.99",
      "keywords": "Google Pom Beanie Charcoal, pom beanie, charcoal pom beanies, Google Beanies, Pom Beanies, charcoal Google pom, beanies, headgear",
      "url": "Google+Pom+Beanie+Charcoal",
      "category": "apparel",
      "subcategory": "apparel"
    },
    {
      "id": "GGOEWXXX0827",
      "name": "Waze Women's Short Sleeve Tee",
      "description": "Made of soft tri-blend jersey fabric, this great t-shirt will help you find your Waze. Made in USA.",
      "features": "<p>Jersey knit</p>\n<p>37.5% cotton, 50% polyester, 12.5% rayon</p>\n<p>Made in the USA</p>",
      "price": "18.99",
      "keywords": "Waze Women's Short Sleeve Tee, Waze Short Sleeve Tee, Waze Women's Tees, Waze Women's tee, waze ladies tees, waze ladies tee, waze short sleeve tees, waze short sleeve tee",
      "url": "Waze+Womens+Short+Sleeve+Tee",
      "category": "apparel",
      "subcategory": "apparel"
    },
    {
      "id": "GGOEWXXX0828",
      "name": "Waze Men's Short Sleeve Tee",
      "description": "Made of soft tri-blend jersey fabric, this great t-shirt will help you find your Waze. Made in USA.",
      "features": "<p>Jersey knit</p>\n<p>37.5% cotton, 50% polyester, 12.5% rayon</p>\n<p>Made in the USA</p>",
      "price": "18.99",
      "keywords": "Waze Men's Short Sleeve Tee, Waze Short Sleeve Tee, Waze Men's Tees, Waze Men's tee, waze mens tees, waze mens tee, waze short sleeve tees, waze short sleeve tee",
      "url": "Waze+Mens+Short+Sleeve+Tee",
      "category": "apparel",
      "subcategory": "apparel"
    },
    {
      "id": "GGOEGBRJ037399",
      "name": "Google Rucksack",
      "description": "Choose to carry your belongings and presentations to your next meeting with the Google Mistral Rucksack!",
      "features": "<p>Size: 13.5 x 6.5 x 17.5</p>\n<p>Ergonomic padded shoulder straps</p>\n<p>Large main compartment with internal laptop compartment</p>\n<p>Easy Snap and Adjustable straps for main compartment access</p>",
      "price": "79.99",
      "keywords": "Mistral Rucksack, Mistral backpack, Mistral Backpack, backpack, bags, bag, Backpack, backpacks, packs, office gear, Bag, Bags, Google Backpack, google backpack, g, google",
      "url": "Google+Rucksack",
      "category": "bags",
      "subcategory": "bags"
    },
    {
      "id": "GGOEGDHJ087399",
      "name": "Google Rolltop Backpack Blue",
      "description": "This stylish Google rolltop backpack will help keep all of your favorite items organized and together while you're on the move.",
      "features": "<p>Size: 12 inches wide x 18.5 inches height x 5.3 inches depth</p>\n<p>TPU Liner</p>\n<p>Internal Organizer for Pens, Phones and Other Small Items</p>\n<p>Large Main Compartment</p>\n<p>Flap Closure for Quick Access or Roll-Top for Expandable Volume and Weather Protection</p>",
      "price": "149.99",
      "keywords": "Google Rolltop Backpack Blue, google backpack, google blue backpack, blue rolltop, Google rolltop, Blue Backpack, backpack, rolltop",
      "url": "Google+Rolltop+Backpack+Blue",
      "category": "bags",
      "subcategory": "bags"
    },
  ],

  orderDummyData: [
    {
      "data": {
        "company": {
          "name": "Lazz",
          "contactperson": {
            "name": "DioneTweedlie",
            "phone": "374-(954)488-9771"
          }
        },
        "price": "€35260,85",
        "dateoforder": "02/29/2016",
        "dateoffinish": "05/18/2017"
      }
    },
    {
      "data": {
        "company": {
          "name": "Centizu",
          "contactperson": {
            "name": "DaltonHatherill",
            "phone": "231-(544)896-2818"
          }
        },
        "price": "€96241,02",
        "dateoforder": "09/29/2015",
        "dateoffinish": "02/26/2017"
      }
    }
  ],

  transactionsDummyData: [
    {
      beginningBalance: 100,
      type: 'Safe',
      countedAmount: 172.24,
      expectedCountedAmount: 200.50,
      overshortAmount: 40.05,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
    {
      beginningBalance: 200,
      type: 'company',
      countedAmount: 182.24,
      expectedCountedAmount: 400.50,
      overshortAmount: 12.05,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
    {
      beginningBalance: 500,
      type: 'Other',
      countedAmount: 192.24,
      expectedCountedAmount: 800.50,
      overshortAmount: 10.05,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
    {
      beginningBalance: 50,
      type: 'company',
      countedAmount: 172.24,
      expectedCountedAmount: 100.50,
      overshortAmount: 3.05,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
    {
      beginningBalance: 300,
      type: 'Safe',
      countedAmount: 162.24,
      expectedCountedAmount: 600.50,
      overshortAmount: 0.75,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
    {
      beginningBalance: 70,
      type: 'company',
      countedAmount: 152.24,
      expectedCountedAmount: 700.50,
      overshortAmount: 0.15,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
    {
      beginningBalance: 900,
      type: 'Manager',
      countedAmount: 172.24,
      expectedCountedAmount: 900.50,
      overshortAmount: 0.05,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
    {
      beginningBalance: 100,
      type: 'Safe',
      countedAmount: 172.24,
      expectedCountedAmount: 100.50,
      overshortAmount: 0.05,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
    {
      beginningBalance: 300,
      type: 'company',
      countedAmount: 172.24,
      expectedCountedAmount: 300.50,
      overshortAmount: 0.05,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
    {
      beginningBalance: 470,
      type: 'company',
      countedAmount: 172.24,
      expectedCountedAmount: 172.19,
      overshortAmount: 0.05,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
    {
      beginningBalance: 550,
      type: 'Safe',
      countedAmount: 172.24,
      expectedCountedAmount: 172.19,
      overshortAmount: 0.05,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
    {
      beginningBalance: 990,
      type: 'Other',
      countedAmount: 172.24,
      expectedCountedAmount: 172.19,
      overshortAmount: 0.05,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
    {
      beginningBalance: 550,
      type: 'Safe',
      countedAmount: 172.24,
      expectedCountedAmount: 172.19,
      overshortAmount: 0.05,
      transactionDate: '2017-11-09T14:18:43.567319Z',
    },
  ]


}
